### ISSUE TITLE
Error in `mepp_deploy_0.52.1/mepp': realloc(): invalid pointer: 0x00000000006c4840

### ISSUE THREAD

**Issue by delmottea** [MEPP-team/MEPP#45]
Hello,
I tried to compile under ubuntu 16.04, but I got an error at start when I run it.
Here is the log :
[error_log.txt](https://github.com/MEPP-team/MEPP/files/1676927/error_log.txt)

I only need it for MSDM2 metric for performance evaluation of my research, is there other implementation easier to use (without graphical interface, like command line or library)?

Best regards

**Comment by mtola** [comment]
Hello,
We don't have any error under Linux, Win and Mac OS X and we test every 6 months every ubuntu since 2008.
Mepp is very stable.
Try to put Nvidia drivers instead of opensource Xorg free drivers. It's my only one idea.

Sorry, no, no other implementation.

**Comment by mtola** [comment]
Second idea, here you use qt5 I saw.

Under 16.04 I think libqglviewer is linked with qt4 so for you 2 solutions :
 - redo a cmake in another build directory with qt4 instead of qt5 and try again
or another solution if you (really...) want to keep qt5 :
- uninstall libqglviewer with apt and make your own compilation of libqglviewer with qt5 (i recommend you to choose libqglviewer 2.6.3)

**Comment by delmottea** [comment]
thanks for fast reply, 
uninstalling libqglviewer-dev and installing libqglviewer-dev-qt4 instead solved the problem

**Comment by mtola** [comment]
Perfect :-)
